apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: sql-server
  template:
    metadata:
      labels:
        component: sql-server
    spec:
      containers:
        - name: sql-server
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
            - name: SA_PASSWORD
              value: "OctopusDeploy_1234"
            - name: ACCEPT_EULA
              value: "Y"