version: '3.4'

services:
  productservice:
    container_name: productservice
    environment:
      - OPSConnectionString=Data Source=octopetshop.czackpbhxo2c.us-east-1.rds.amazonaws.com;Initial Catalog=OctoPetShop; User ID=admin; Password=OctopusDeploy_1234
    image: pjgcreations/octopetshop-productservice
    depends_on: 
      - "database"
    networks:
      - octonet

  shoppingcartservice:
    container_name: shoppingcartservice
    image: pjgcreations/octopetshop-shoppingcartservice
    environment:
      - OPSConnectionString=Data Source=octopetshop.czackpbhxo2c.us-east-1.rds.amazonaws.com;Initial Catalog=OctoPetShop; User ID=admin; Password=OctopusDeploy_1234
    depends_on: 
      - "database"
    networks:
      - octonet

  web:
    container_name: web
    image: pjgcreations/octopetshop-web
    environment:
      - ProductServiceBaseUrl=http://productservice
      - ShoppingCartServiceBaseUrl=http://shoppingcartservice
    ports:
      - "80:80"
      - "443:443"
    depends_on: 
      - "shoppingcartservice"
      - "productservice"
    networks:
      - octonet

  database:
    container_name: database
    environment:
      - DbUpConnectionString=Data Source=octopetshop.czackpbhxo2c.us-east-1.rds.amazonaws.com;Initial Catalog=OctoPetShop; User ID=admin; Password=OctopusDeploy_1234
    image: pjgcreations/octopetshop-database
    networks:
      - octonet
      
networks:
  octonet:
