version: '3.4'

services:
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "OctopusDeploy_1234"
      ACCEPT_EULA: "Y"
    networks:
      - octonet
  
  productservice:
    container_name: productservice
    environment:
      - OPSConnectionString=Data Source=sql-server;Initial Catalog=OctoPetShop; User ID=sa; Password=OctopusDeploy_1234
    image: pjgcreations/octopetshop-productservice
    depends_on: 
      - "database"
    networks:
      - octonet

  shoppingcartservice:
    container_name: shoppingcartservice
    image: pjgcreations/octopetshop-shoppingcartservice
    environment:
      - OPSConnectionString=Data Source=sql-server;Initial Catalog=OctoPetShop; User ID=sa; Password=OctopusDeploy_1234
    depends_on: 
      - "database"
    networks:
      - octonet

  web:
    container_name: web
    image: pjgcreations/octopetshop-web
    environment:
      - ProductServiceBaseUrl=http://productservice
      - ShoppingCartServiceBaseUrl=http://shoppingcartservice
    ports:
      - "80:80"
      - "443:443"
    depends_on: 
      - "shoppingcartservice"
      - "productservice"
    networks:
      - octonet

  database:
    container_name: database
    environment:
      - DbUpConnectionString=Data Source=sql-server;Initial Catalog=OctoPetShop; User ID=sa; Password=OctopusDeploy_1234
    image: pjgcreations/octopetshop-database
    depends_on: 
      - "sql-server" 
    networks:
      - octonet

networks:
  octonet:
