apiVersion: v1
kind: Service
metadata:
  name: octopetshop-web-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: web
  ports:
    - port: 80
      targetPort: 80
      name: http-port
    - port: 443
      targetPort: 443
      name: https-port